# Generated by Django 2.2.4 on 2019-11-20 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='request',
            new_name='bid',
        ),
    ]
