# Generated by Django 2.2.4 on 2019-11-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20191120_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Urgency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='urgency',
            field=models.ManyToManyField(to='payment.Urgency'),
        ),
    ]
