# Generated by Django 2.2.4 on 2019-11-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20191121_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urgency',
            name='name',
            field=models.CharField(choices=[('Urgent', 'Urgent'), ('Important', 'Important'), ('Flexible', 'Flexible')], max_length=50),
        ),
    ]
