# Generated by Django 2.2.4 on 2019-11-21 10:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20191121_0641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urgency',
            name='urgency_tag',
        ),
        migrations.AddField(
            model_name='urgency',
            name='urgency',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
