# Generated by Django 2.2.4 on 2019-11-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_auto_20191121_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='urgency',
        ),
        migrations.AlterField(
            model_name='urgency',
            name='urgency_tag',
            field=models.CharField(max_length=50),
        ),
    ]
