# Generated by Django 2.2.4 on 2019-11-25 14:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_orders_urgency'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='full_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
