# Generated by Django 2.2.4 on 2019-11-25 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_orders_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='bid',
            new_name='run_request',
        ),
    ]
