# Generated by Django 2.2.4 on 2019-11-25 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_auto_20191125_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='cost',
        ),
    ]
