# Generated by Django 2.2.4 on 2019-11-26 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_remove_orders_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='cost',
            field=models.IntegerField(null=True),
        ),
    ]
