# Generated by Django 2.2.4 on 2019-11-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_orders_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
