# Generated by Django 2.2.4 on 2019-11-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0015_auto_20191126_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='contact',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
