# Generated by Django 2.2.4 on 2019-11-18 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191118_0424'),
    ]

    operations = [
        migrations.DeleteModel(
            name='orders',
        ),
    ]
