# Generated by Django 2.2.4 on 2019-11-15 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191115_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='description',
            new_name='request',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='name',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='quantity',
        ),
    ]
